version: '3.9'

services:

  dev_mongo_db:
    image: mongo
    # restart: always
    volumes:
      - dev_mongo_db_data:/data/db
    ports:
      - 27017:27017
    networks:
      - mojo

volumes:
  dev_mongo_db_data:


networks:
  mojo:
